name: Validate and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install vnu-jar stylelint stylelint-config-standard

      - name: Get path to vnu.jar
        run: echo "JAR_PATH=$(node -e "console.log(require('vnu-jar'))")" >> $GITHUB_ENV

      - name: Find HTML & CSS files (excluding node_modules)
        run: |
          HTML_FILES=$(find . -type f -name "*.html" -not -path "*/node_modules/*")
          CSS_FILES=$(find . -type f -name "*.css"  -not -path "*/node_modules/*")
          if [ -z "$HTML_FILES" ]; then
            echo "Geen HTML-bestanden gevonden."
            exit 0
          fi
          {
            echo "HTML_FILES<<EOF"
            echo "$HTML_FILES"
            echo "EOF"
            echo "CSS_FILES<<EOF"
            echo "$CSS_FILES"
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Convert HTML files to UTF-8
        run: |
          for f in $HTML_FILES; do
            if file -i "$f" | grep -vq 'charset=utf-8'; then
              echo "Converting $f to UTF-8"
              iconv -f WINDOWS-1252 -t UTF-8 "$f" -o "$f".utf8 && mv "$f".utf8 "$f"
            fi
          done

      - name: Validate HTML
        run: |
          java -jar "$JAR_PATH" --errors-only --format text $HTML_FILES

      - name: Validate CSS
        run: npx stylelint "$CSS_FILES"

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: "--verbose --no-progress $HTML_FILES"

  deploy:
    needs: validate-html
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }} # Alleen bij push, niet bij PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .