name: HTML Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install vnu-jar via npm
        run: npm install vnu-jar

      - name: Path to vnu.jar
        id: vnu
        run: |
          JAR_PATH=$(node -e "console.log(require('vnu-jar'))")
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

      - name: Run HTML validation (report)
        run: |
          mkdir -p reports
          java -jar "$JAR_PATH" --errors-only --format html $(find . -type f -name "*.html") > reports/report.html || true
          java -jar "$JAR_PATH" --errors-only --format text $(find . -type f -name "*.html") > reports/report.txt || true

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: html-validation-report
          path: reports/

      - name: Fail job if errors found
        run: java -jar "$JAR_PATH" --errors-only --format text .
